[tool.poetry]
name = "shiki.py"
version = "0.1.0"
description = ""
authors = ["Snayt1k3 <snayt1k3twitch@gmail.com>"]
readme = "README.md"
packages = [{include = "shikimori"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.3"
aiohttp = "^3.9.1"
tomli = "^2.0.1"
[build-system]
requires = [
    "setuptools",
    "tomli",
]
build-backend = "setuptools.build_meta"
